// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdjbxkeraqyjzokrkzqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkamJ4a2VyYXF5anpva3JrenFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjYyMzgsImV4cCI6MjA2NDM0MjIzOH0.ky2sOxbEjEfE83ULeMhcjBSHFur7GpO8caMRxbwdNxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);